name: music_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  build_runner: ^2.4.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  http: ^1.1.0
  get: ^4.3.8
  intl: ^0.18.1
  json_serializable: ^6.7.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
  - family: poppins
    fonts:
      - asset: fonts/Poppins-Regular.ttf
  - family: inter
    fonts:
      - asset: fonts/Inter-Regular.ttf
  - family: monserrat
    fonts:
      - asset: fonts/Montserrat-Regular.ttf
